version: '3'

services:
  mongo:
    image: "mongo"
    container_name: "mongo"
  vessel-service:
#    build: ./vessel-service
    image: "vessel-service"
    container_name: "vessel-service"
    links:
      - "mongo"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
    ports:
      - "5052:50051"
